export const achievements2024 = [
    {
        "responsible_researchers": "researcher_011",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Identification of Gas Mixture Components with Multichannel Hierarchical Analysis of Time-Resolved Hyperspectral Data",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-03-24",
        "Journal Name": "ACS Sensors",
        "Impact Factor": "8.3",
        "Contribution Rate (%)": "34",
        "JCR Top (%)": "3.77",
        "Number of Acknowledged Papers": "3"
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Deciphering the Toxic Effects of Polystyrene Nanoparticle on Erythropoiesis at Single Cell Resolution",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-09-06",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Highly Aligned Ternary Nanofiber Matrices Loaded with Mxene Expedite Regeneration of Volumetric Muscle Loss",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-09-06",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Academic Conference",
        "Title and Content": "멀티오믹스 데이터기반 MRONJ 발병기전 바이오마커 발굴 및 실증 연구",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-10-20",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Clinical Application of Multi-Omics Biomarkers for the Diagnosis and Prediction of MRONJ",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-03",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Awards and Honors",
        "Title and Content": "2024년 부산대학교 우수연구자상 수상\n부산대학교 우수연구자",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-12-17",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_011",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Interleaved frequency comb by chip-scale acousto-optic phase modulation at polydimethylsiloxane for higher-resolution direct plasmonic comb spectroscopy.",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-04-14",
        "Journal Name": "PhotoniX",
        "Impact Factor": "15.7",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "5.04",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Time-dependent reduction of somatic variants in lichen striatus as evidence for the clearance of mutated skin cells",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-31",
        "Journal Name": "Journal of the American Academy of Dermatology",
        "Impact Factor": "12.8",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "1.06",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Deciphering the Toxic Effects of Polystyrene Nanoparticle on Erythropoiesis at Single Cell Resolution. ",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-01",
        "Journal Name": "Zoological Research",
        "Impact Factor": "4",
        "Contribution Rate (%)": "100",
        "JCR Top (%)": "2.21",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Exploring the complex link between obesity and intelligence: Evidence from systematic review, updated meta-analysis, and Mendelian randomization",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-12-01",
        "Journal Name": "Obesity Reviews",
        "Impact Factor": "10.867",
        "Contribution Rate (%)": "60",
        "JCR Top (%)": "7.53",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_018",
        "group_id": "4",
        "Achievement Name": "Academic Conference",
        "Title and Content": "A Novel CNN Filter Inspired by Order Theory\n심사결과발표",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-12-10",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Zebrafish embryo toxicity to ssDNA-wrapped carbon nanotube dispersion: From whole-body to single-cell resolution",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-04-00",
        "Journal Name": "Carbon",
        "Impact Factor": "10.5",
        "Contribution Rate (%)": "12.5",
        "JCR Top (%)": "11.39",
        "Number of Acknowledged Papers": "8"
    },
    {
        "responsible_researchers": "researcher_010",
        "group_id": "2",
        "Achievement Name": "Academic Conference",
        "Title and Content": "인공지능 3D 프린팅 공정 최적화를 위한 강화학습 활용 방안에 대한 연구\n2024 한국정밀공학회 추계학술대회",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-29",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_010",
        "group_id": "2",
        "Achievement Name": "Awards and Honors",
        "Title and Content": "인공지능 3D 프린팅 공정 최적화를 위한 강화학습 활용 방안에 대한 연구 (우수발표논문상)\n2024 한국정밀공학회 추계학술대회",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-29",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_016",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Modulating vascular smooth muscle cell phenotype via Wnt-Independent FRZB pathways",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-01",
        "Journal Name": "Archives of Biochemistry and Biophysics",
        "Impact Factor": "3.391",
        "Contribution Rate (%)": "30",
        "JCR Top (%)": "19.48",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_012",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Silicon photodiode-competitive 2D vertical photodetector",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-24",
        "Journal Name": "npj Flexible Electronics",
        "Impact Factor": "12.3",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "1.98",
        "Number of Acknowledged Papers": "2"
    },
    {
        "responsible_researchers": "researcher_012",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Robust van der Waals metal mask for residue-free and all-solid 2D material engineering",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-11-12",
        "Journal Name": "Advanced Functional Materials",
        "Impact Factor": "18.5",
        "Contribution Rate (%)": "100",
        "JCR Top (%)": "4.33",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "International Technology Exchange Information",
        "Title and Content": "미국 현지 및 온라인 네트워킹 진행\nUC Davis 방문 협의",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-00",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_012",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Ultimate Scaling of the Metal-MoS2 Interface Achieving High Performance Nanoscale Schottky Diodes via Conductive Atomic Force Microscopy",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-04-08",
        "Journal Name": "Small",
        "Impact Factor": "13",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "7.26",
        "Number of Acknowledged Papers": "2"
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Academic Conference",
        "Title and Content": "MOLECULAR ENGINEERING APPROACHES TO PEROVSKITE SOLAR CELLS\nRSC Next Generation Materials for Solar Photovoltaics 2025",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-16",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "Awards and Honors",
        "Title and Content": "PNU-Star (부산대학교)",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2025-01-23",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "International Cooperation Achievements (Recruitment/Dispatch)",
        "Title and Content": "캐나다 빅토리아대학교 연구원 채용 완료",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-10-17",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "International Cooperation Achievements (Recruitment/Dispatch)",
        "Title and Content": "캐나다 빅토리아대학교 연구원\n신규 연구인력 채용 관련 논의 및 연구프로그램 진행",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-15 - 2025-02-02",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "International Cooperation Achievements (Recruitment/Dispatch)",
        "Title and Content": "스위스 ZHAW 연구진\n취리히응용과학대학교 방문 특강 및 공동연구",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-10 - 2025-01-15",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "International Cooperation Achievements (International Collaboration)",
        "Title and Content": "캐나다빅토리아 (MOU)",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-10-17",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "International Technology Exchange Information",
        "Title and Content": "자문\n정효영 교수",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-01-21",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_012",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Ultrafast hot carrier extraction and diffusion in MoS2/Au van der Waals electrode interface",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-03",
        "Journal Name": "Science Advances",
        "Impact Factor": "11.7",
        "Contribution Rate (%)": "20",
        "JCR Top (%)": "8.21",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_014",
        "group_id": "3",
        "Achievement Name": "Promotion Achievements",
        "Title and Content": "자문\n부산일보사 문화사업국, 유튜브 채널 ‘뭐볼랭’에 센터 홍보",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-09-26",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_012",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Hot carrier diffusion-assisted ideal carrier multiplication in monolayer MoSe2",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-04-08",
        "Journal Name": "Materials Horizons",
        "Impact Factor": "12.2",
        "Contribution Rate (%)": "17",
        "JCR Top (%)": "8.88",
        "Number of Acknowledged Papers": "6"
    },
    {
        "responsible_researchers": "researcher_012",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Augmented Extraction Efficiency of a Hot D Exciton in MoS2 via Intervalley Scattering",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-09-03",
        "Journal Name": "Nano Letters",
        "Impact Factor": "9.627",
        "Contribution Rate (%)": "20",
        "JCR Top (%)": "10.06",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_010",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "High-strength of additive-manufactured PEEK and Ti6Al4V structure via warm isostatic pressing: applications in medical implants and injection moulds",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-15",
        "Journal Name": "Virtual and Physical Prototyping",
        "Impact Factor": "4.231",
        "Contribution Rate (%)": "30",
        "JCR Top (%)": "7.35",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_010",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "In-situ autocalibrated electrospinning process via U-Net based real-time monitoring",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-03-15",
        "Journal Name": "Journal of Manufacturing Processes",
        "Impact Factor": "6.1",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "17.65",
        "Number of Acknowledged Papers": "2"
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Professional Research Personnel Training (Degree Completion)",
        "Title and Content": "김민준 (석사)",
        "Domestic/International": "",
        "Date of Occurrence": "2025-02-28",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Professional Research Personnel Training (Degree Completion)",
        "Title and Content": "한승우 (석사)",
        "Domestic/International": "",
        "Date of Occurrence": "2025-02-28",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Professional Research Personnel Training (Degree Completion)",
        "Title and Content": "황보람 (박사)",
        "Domestic/International": "",
        "Date of Occurrence": "2025-02-28",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Professional Research Personnel Training (Degree Completion)",
        "Title and Content": "김지수 (석사)",
        "Domestic/International": "",
        "Date of Occurrence": "2025-02-28",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Paper",
        "Title and Content": "Long-term reliable wireless H₂ gas sensor via repeatable thermal refreshing of palladium nanowire",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-10-09",
        "Journal Name": "Nature Communications",
        "Impact Factor": "14.7",
        "Contribution Rate (%)": "33",
        "JCR Top (%)": "5.97",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Paper",
        "Title and Content": "Highly accurate, efficient, and fabrication tolerance-aware nanostructure prediction for high-performance optoelectronic devices",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-12-03",
        "Journal Name": "Scientific Reports",
        "Impact Factor": "3.8",
        "Contribution Rate (%)": "33",
        "JCR Top (%)": "18.66",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Paper",
        "Title and Content": "Micromachined PVA (Poly(vinyl alcohol)) Sacrificial Layer for Facile and Scalable Demonstration of Highly Reproducible Porous-Type Pressure Sensor",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-10-11",
        "Journal Name": "ACS Applied Polymer Materials",
        "Impact Factor": "4.5",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "23.16",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_004",
        "group_id": "1",
        "Achievement Name": "Professional Research Personnel Training (Degree Completion)",
        "Title and Content": "유채린 (박사)",
        "Domestic/International": "",
        "Date of Occurrence": "2025-02-28",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Paper",
        "Title and Content": "Photo-Thermal Approaches on Polyimide Film for Demonstration of Sub-50 μm Polymer Stencil Mask",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-04-01",
        "Journal Name": "Advanced Electronic Materials",
        "Impact Factor": "16.6",
        "Contribution Rate (%)": "33",
        "JCR Top (%)": "24.02",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Intellectual Property Rights (Patent)",
        "Title and Content": "PDMS 기반 미세유체 채널의 표면 및 이를 처리하는 플라즈마 장치 및 방법",
        "Domestic/International": "",
        "Date of Occurrence": "",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": "출원"
    },
    {
        "responsible_researchers": "researcher_006",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Tailor-Made Buffer Materials: Advancing Uniformity and Stability in Perovskite Solar Cells",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-11-13",
        "Journal Name": "Advanced Energy Materials",
        "Impact Factor": "27.8",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "2.92",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_013",
        "group_id": "3",
        "Achievement Name": "Technology Transfer",
        "Title and Content": "PDMS 기반 미세유체 채널의 표면 및 이를 처리하는 플라즈마 장치 및 방법",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_014",
        "group_id": "3",
        "Achievement Name": "Paper",
        "Title and Content": "Highly accurate, efficient, and fabrication tolerance-aware nanostructure prediction for high-performance optoelectronic devices",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-12-03",
        "Journal Name": "Scientific Reports",
        "Impact Factor": "3.8",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "18.66",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "Awards and Honors",
        "Title and Content": "우수강의상\n한국교양기초교육원",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-10-28",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "Awards and Honors",
        "Title and Content": "우수심사위원상\n(Editor's Pick)",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-09-27",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "International Cooperation Achievements (Recruitment/Dispatch)",
        "Title and Content": "퍼듀대학교 연구원\nIndianapolis University",
        "Domestic/International": "International",
        "Date of Occurrence": "2023-03-01 - 현재",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_002",
        "group_id": "1",
        "Achievement Name": "Awards and Honors",
        "Title and Content": "Best Poster Award\n한국화학공학회",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-29",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Point-of-Care-Testing NO3−N Detection Technology with Selected Transition-Metal-Based Colorimetric Sensor Arrays",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-00",
        "Journal Name": "ACS Sensors",
        "Impact Factor": "8.3",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "3.77",
        "Number of Acknowledged Papers": "2"
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Intellectual Property Rights (Patent)",
        "Title and Content": "알부민을 검출하는 비색성 센서 어레이, 이를 포함하는 분석장치 및 이를 이용한 비색성 센서",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-12-30",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Intellectual Property Rights (Patent)",
        "Title and Content": "히스티딘메틸레이트를 검출하는 비색성 센서 어레이,이를 포함하는 분석장치 및 이를 이용한 휘발성 유기화합물 검출센서",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-12-30",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Intellectual Property Rights (Patent)",
        "Title and Content": "유기금속 구조체 및 그래핀 옥사이드 복합체, 유기금속 구조체 및 그래핀 옥사이드 복합체 제조 방법 및 이를 포함 하여 암모니아 가스 검출용 유기금속 구조체",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-12-30",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Microcapillary-Derived Plasmonic-Enhanced Cluster through the Self-Assembly Process for Breast Cancer Diagnosis",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-00",
        "Journal Name": "ACS Sensors",
        "Impact Factor": "8.3",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "3.77",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_001",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "M13 bacteriophage-based high-sensitivity Fabry-Perot etalon for detecting humidity and volatile organic compounds",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-08-00",
        "Journal Name": "Optics Express",
        "Impact Factor": "3.2",
        "Contribution Rate (%)": "10",
        "JCR Top (%)": "30.25",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_009",
        "group_id": "2",
        "Achievement Name": "Paper",
        "Title and Content": "Artificial Modulation of the Hydrogen Evolution Reaction Kinetics via Control of Grain Boundaries Density in Mo2C Through Laser Processing",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-25",
        "Journal Name": "Advanced Functional Materials",
        "Impact Factor": "18.5",
        "Contribution Rate (%)": "25",
        "JCR Top (%)": "4.33",
        "Number of Acknowledged Papers": "4"
    },
    {
        "responsible_researchers": "researcher_011",
        "group_id": "2",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Selective Laser Patterning of hBN-encapsulated TMDs and Graphene: Melting Point Effects on Material Removal",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-00",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_011",
        "group_id": "2",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Laser Induced Graphene Heat Accumulation Effect on Lignin/PEO Film by Comparison Continuous and Femtosecond Pulse Laser",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-00",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_011",
        "group_id": "2",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Black Ice Recognition by Time-division Multiplexing Based Multispectral LiDAR System for Autonomous Driving",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-00",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_011",
        "group_id": "2",
        "Achievement Name": "Academic Conference",
        "Title and Content": "Multifunctional 3D Nanoprinting: Fabrication and Applications of Structures Using Various Nanoparticles",
        "Domestic/International": "Domestic",
        "Date of Occurrence": "2024-11-00",
        "Journal Name": "",
        "Impact Factor": "",
        "Contribution Rate (%)": "",
        "JCR Top (%)": "",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_004",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Advanced Facial Mask Using Roll-to-Roll Processed Superhydrophobic Vertically Aligned Carbon Nanotubes for Enhanced Antiviral Effects and Reusability",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-03-10",
        "Journal Name": "SusMat",
        "Impact Factor": "18.7",
        "Contribution Rate (%)": "40",
        "JCR Top (%)": "2.2",
        "Number of Acknowledged Papers": "50"
    },
    {
        "responsible_researchers": "researcher_004",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Influence of twist angle and diameter on yarn densification and mechanical-electrical properties of multi-ply carbon nanotube yarns",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-14",
        "Journal Name": "Journal of Materials Research and Technology",
        "Impact Factor": "8.8",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "6.77",
        "Number of Acknowledged Papers": "50"
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Self-supervised learning for effective denoising of flow fields",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-10-11",
        "Journal Name": "Physics of Fluids",
        "Impact Factor": "4.1",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "1.05",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Flow field recovery in restricted domains using a generative adversarial network framework",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-12-03",
        "Journal Name": "Physics of Fluids",
        "Impact Factor": "4.1",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "1.05",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Enhanced retrospective forecasting in dissipative dynamical systems using transformer and multi-scale ESRGAN models",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-12-03",
        "Journal Name": "Results in Engineering",
        "Impact Factor": "5.6",
        "Contribution Rate (%)": "34",
        "JCR Top (%)": "5.52",
        "Number of Acknowledged Papers": "3"
    },
    {
        "responsible_researchers": "researcher_017",
        "group_id": "4",
        "Achievement Name": "Paper",
        "Title and Content": "Exploring Near-Wake Structures: Bio-Inspired Convergent-Divergent Riblets on Circular Bluff Bodies",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-08-24",
        "Journal Name": "Journal of Fluids Engineering",
        "Impact Factor": "1.8",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "54.64",
        "Number of Acknowledged Papers": "2"
    },
    {
        "responsible_researchers": "researcher_005",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "An impermeable copper surface monolayer with high-temperature oxidation resistance",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-02-08",
        "Journal Name": "Nature Communications",
        "Impact Factor": "14.7",
        "Contribution Rate (%)": "10",
        "JCR Top (%)": "5.97",
        "Number of Acknowledged Papers": "10%"
    },
    {
        "responsible_researchers": "researcher_003",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "3D bioprintable Mg2+-incorporated hydrogels tailored for regeneration of volumetric muscle loss",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-14",
        "Journal Name": "Theranostics",
        "Impact Factor": "12.4",
        "Contribution Rate (%)": "40",
        "JCR Top (%)": "4.23",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_003",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Harnessing the Intradermal Delivery of Hair Follicle Dermal Papilla Cell Spheroids for Hair Follicle Regeneration in Nude Mice",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-01-13",
        "Journal Name": "Biomaterials Research",
        "Impact Factor": "8.1",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "10.57",
        "Number of Acknowledged Papers": ""
    },
    {
        "responsible_researchers": "researcher_003",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Versatile and marvelous potentials of polydeoxyribonucleotide for tissue engineering and regeneration",
        "Domestic/International": "International",
        "Date of Occurrence": "2025-04-01",
        "Journal Name": "Biomaterials Research",
        "Impact Factor": "8.1",
        "Contribution Rate (%)": "33",
        "JCR Top (%)": "10.57",
        "Number of Acknowledged Papers": "3"
    },
    {
        "responsible_researchers": "researcher_003",
        "group_id": "1",
        "Achievement Name": "Paper",
        "Title and Content": "Studies on cytocompatibility of human dermal fibroblasts on carbon nanofiber nanoparticle?containing bioprinted constructs",
        "Domestic/International": "International",
        "Date of Occurrence": "2024-09-13",
        "Journal Name": "Discover Nano",
        "Impact Factor": "5.5",
        "Contribution Rate (%)": "50",
        "JCR Top (%)": "90.06",
        "Number of Acknowledged Papers": ""
    }
]